name: Tests and linters

on: [push, pull_request, workflow_dispatch]

jobs:

  test-on-different-versions:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [3.9, "3.10", 3.11, 3.12, 3.13]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install tox
      - run: tox
        env:
          TOXENV: ${{ matrix.python-version }}
  test-coverage:
    name: Run tests with coverage
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov=core --cov-report=json
      - name: Upload coverage to Codecov (arg token)
        uses: codecov/codecov-action@main
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - name: Upload coverage to Codecov (env token)
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: | 
         curl -Os https://uploader.codecov.io/latest/linux/codecov
         find . -iregex "coverage.*"
         chmod +x codecov 
         ./codecov -t ${CODECOV_TOKEN}
  linters:
    name: Run linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [flake8, pydocstyle, mypy, pylint]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - run: pip install tox
      - run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}