name: Release Docker Application
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/optiattack:latest .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/optiattack:latest ${{ secrets.DOCKER_HUB_USERNAME }}/optiattack:${{ github.ref_name }}

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/optiattack:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/optiattack:${{ github.ref_name }}

      - name: Run and test container
        run: |
          docker run --rm \
            -p 13000:13000 \
            ${{ secrets.DOCKER_HUB_USERNAME }}/:${{ github.ref_name }} \
            --enable_ui True &

          sleep 20
          curl -sSf http://host.docker.internal:13000 || exit 1
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install setuptools wheel twine

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          cd client/
          python setup.py sdist bdist_wheel
          twine upload dist/*
